# 관련정보는 스프링부트 메뉴얼에서 찾아볼 수 있다

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create # app 실행시점에 entity초기화 후 table 만들어주는 모드
    properties:
      hibernate:
#        show_sql: true  >> sout으로 보여줌, logger가 아니라서 쓰면 안됨
        format_sql: true

logging.level:
  org.hibernate.SQL: debug  # sql을 logger로 보여줌
  org.hibernate.orm.jdbc.bind: trace